using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class UserPlaneScript : PlaneMoveScript
{
    private void Awake()
    {
        //Set the name of the plane to the name generated by the PlaneNamer function in the SpawnerScript.
        gameObject.name = SpawnerScript.instance.PlaneNamer();
    }

    //Selection function that is called when a user controllable plane is clicked.
    private void OnMouseUpAsButton()
    {
        //Checks if the game state is playing and the previous selection is not the current selection.
        if (((GameManager.instance.State == GameState.Playing) && (GameManager.instance.PreviousSelection != gameObject)) || (GameManager.instance.State == GameState.EndOfRound))
        {
            if (GameManager.instance.PreviousSelection != null)
            {
                //Calls the PlaneDeselection function in the Game Manager.
                GameManager.instance.PlaneDeselection();
            }
            //Sets the current selection to the previous selection.
            GameManager.instance.PreviousSelection = gameObject;
            //Calls the PlaneSelection function in the Game Manager.
            GameManager.instance.PlaneSelection();
        }
    }
}
